/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeDrawdown"
      | "deposit"
      | "distributeYield"
      | "getLPBalance"
      | "getPSPPosition"
      | "getPoolState"
      | "processConvertedRepayment"
      | "repay"
      | "requestDrawdown"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "DrawdownExecuted"
      | "LiquidityShortfall"
      | "PoolInitialized"
      | "RepaymentProcessed"
      | "RepaymentReceived"
      | "Withdrawn"
      | "YieldDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeDrawdown",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPSPPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processConvertedRepayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDrawdown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "completeDrawdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLPBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPSPPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processConvertedRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDrawdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [lp: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lp: string, amount: bigint];
  export interface OutputObject {
    lp: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawdownExecutedEvent {
  export type InputTuple = [psp: AddressLike, amount: BigNumberish];
  export type OutputTuple = [psp: string, amount: bigint];
  export interface OutputObject {
    psp: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityShortfallEvent {
  export type InputTuple = [
    psp: AddressLike,
    deficit: BigNumberish,
    requestId: BigNumberish
  ];
  export type OutputTuple = [psp: string, deficit: bigint, requestId: bigint];
  export interface OutputObject {
    psp: string;
    deficit: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    drawdownLimit: BigNumberish,
    pspRate: BigNumberish,
    apy: BigNumberish
  ];
  export type OutputTuple = [
    drawdownLimit: bigint,
    pspRate: bigint,
    apy: bigint
  ];
  export interface OutputObject {
    drawdownLimit: bigint;
    pspRate: bigint;
    apy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentProcessedEvent {
  export type InputTuple = [
    psp: AddressLike,
    principal: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [psp: string, principal: bigint, fee: bigint];
  export interface OutputObject {
    psp: string;
    principal: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentReceivedEvent {
  export type InputTuple = [
    psp: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [psp: string, token: string, amount: bigint];
  export interface OutputObject {
    psp: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [lp: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lp: string, amount: bigint];
  export interface OutputObject {
    lp: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributedEvent {
  export type InputTuple = [totalAmount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [totalAmount: bigint, timestamp: bigint];
  export interface OutputObject {
    totalAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPool extends BaseContract {
  connect(runner?: ContractRunner | null): IPool;
  waitForDeployment(): Promise<this>;

  interface: IPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeDrawdown: TypedContractMethod<
    [psp: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  distributeYield: TypedContractMethod<
    [lps: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getLPBalance: TypedContractMethod<
    [lp: AddressLike],
    [[bigint, bigint] & { deposited: bigint; claimable: bigint }],
    "view"
  >;

  getPSPPosition: TypedContractMethod<
    [psp: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        repaid: boolean;
      }
    ],
    "view"
  >;

  getPoolState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalLiquidity: bigint;
        availableLiquidity: bigint;
        drawdownLimit: bigint;
        pspRatePerDay: bigint;
        investorAPY: bigint;
      }
    ],
    "view"
  >;

  processConvertedRepayment: TypedContractMethod<
    [psp: AddressLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  repay: TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  requestDrawdown: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeDrawdown"
  ): TypedContractMethod<
    [psp: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeYield"
  ): TypedContractMethod<
    [lps: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLPBalance"
  ): TypedContractMethod<
    [lp: AddressLike],
    [[bigint, bigint] & { deposited: bigint; claimable: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPSPPosition"
  ): TypedContractMethod<
    [psp: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        repaid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalLiquidity: bigint;
        availableLiquidity: bigint;
        drawdownLimit: bigint;
        pspRatePerDay: bigint;
        investorAPY: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processConvertedRepayment"
  ): TypedContractMethod<
    [psp: AddressLike, usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestDrawdown"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "DrawdownExecuted"
  ): TypedContractEvent<
    DrawdownExecutedEvent.InputTuple,
    DrawdownExecutedEvent.OutputTuple,
    DrawdownExecutedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityShortfall"
  ): TypedContractEvent<
    LiquidityShortfallEvent.InputTuple,
    LiquidityShortfallEvent.OutputTuple,
    LiquidityShortfallEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentProcessed"
  ): TypedContractEvent<
    RepaymentProcessedEvent.InputTuple,
    RepaymentProcessedEvent.OutputTuple,
    RepaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentReceived"
  ): TypedContractEvent<
    RepaymentReceivedEvent.InputTuple,
    RepaymentReceivedEvent.OutputTuple,
    RepaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributed"
  ): TypedContractEvent<
    YieldDistributedEvent.InputTuple,
    YieldDistributedEvent.OutputTuple,
    YieldDistributedEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "DrawdownExecuted(address,uint256)": TypedContractEvent<
      DrawdownExecutedEvent.InputTuple,
      DrawdownExecutedEvent.OutputTuple,
      DrawdownExecutedEvent.OutputObject
    >;
    DrawdownExecuted: TypedContractEvent<
      DrawdownExecutedEvent.InputTuple,
      DrawdownExecutedEvent.OutputTuple,
      DrawdownExecutedEvent.OutputObject
    >;

    "LiquidityShortfall(address,uint256,uint256)": TypedContractEvent<
      LiquidityShortfallEvent.InputTuple,
      LiquidityShortfallEvent.OutputTuple,
      LiquidityShortfallEvent.OutputObject
    >;
    LiquidityShortfall: TypedContractEvent<
      LiquidityShortfallEvent.InputTuple,
      LiquidityShortfallEvent.OutputTuple,
      LiquidityShortfallEvent.OutputObject
    >;

    "PoolInitialized(uint256,uint256,uint256)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;

    "RepaymentProcessed(address,uint256,uint256)": TypedContractEvent<
      RepaymentProcessedEvent.InputTuple,
      RepaymentProcessedEvent.OutputTuple,
      RepaymentProcessedEvent.OutputObject
    >;
    RepaymentProcessed: TypedContractEvent<
      RepaymentProcessedEvent.InputTuple,
      RepaymentProcessedEvent.OutputTuple,
      RepaymentProcessedEvent.OutputObject
    >;

    "RepaymentReceived(address,address,uint256)": TypedContractEvent<
      RepaymentReceivedEvent.InputTuple,
      RepaymentReceivedEvent.OutputTuple,
      RepaymentReceivedEvent.OutputObject
    >;
    RepaymentReceived: TypedContractEvent<
      RepaymentReceivedEvent.InputTuple,
      RepaymentReceivedEvent.OutputTuple,
      RepaymentReceivedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "YieldDistributed(uint256,uint256)": TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
    YieldDistributed: TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
  };
}
