/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldReserve,
  IYieldReserveInterface,
} from "../../../src/interfaces/IYieldReserve";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeeReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "lp",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "YieldPaid",
    type: "event",
  },
  {
    inputs: [],
    name: "getReserveBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYieldReserve__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldReserveInterface {
    return new Interface(_abi) as IYieldReserveInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldReserve {
    return new Contract(address, _abi, runner) as unknown as IYieldReserve;
  }
}
